# Site settings
title: Old Time Gringo
email: contact@oldtimegringo.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: ""
#url: "http://localhost:4000"
url: "https://oldtimegringo.github.io"

# Build settings
paginate: 2
paginate_path: "/blog/page:num"
markdown: kramdown
permalink: pretty
highlighter: rouge