# Site settings
title: Old Time Gringo
email: contact@oldtimegringo.com
description: "Old Time Gringo Official Website"
baseurl: ""
#url: "http://localhost:4000"
#url: "oldtimegringo.com"

# Build settings
paginate: 2
paginate_path: "/blog/page:num"
markdown: kramdown
permalink: pretty
#highlighter: rouge
